spring:
  application:
    name: "OnlineOfflineIndicator"
  data:
    redis:
      host: "localhost"
      port: 6379
      lettuce:
        pool:
          enabled: true
          min-idle: 0
          max-active: 10
          max-idle: 2
  cache:
    type: redis
